### ISSUE TITLE
Super cool! Had two questions to better understand how this works...

### ISSUE THREAD

**Issue by luketchang** [oasislabs/ready-layer-two#3]
I was reading through the repo to get a better understanding of contract development in Rust and this all looks really cool! I had two technical questions though, if you didn't mind me asking. 

1) In the typescript client services files, when you call `gateway.rpc(address, payload, options)`, how does the remote node executing your request know which contract function you are calling? I might be missing something huge but it seems like the contract somehow can "magically" infer which contract function you are calling based on the payload you pass in?

2) Does the current repo actually have Oasis nodes test the submitted models against the secret test data? I saw that there is an `evaluation_program` field in the Rust contract but I don't see it being used anywhere. If not, do you know how you would instruct a node to run the evaluation script on the submitted models?

**Comment by nhynes** [comment]
> how does the remote node executing your request know which contract function you are calling?

Good question! You're actually exactly right about the contract inferring the function from the payload. The "magical" part is that the Oasis Eth/WASI SDK [generates the dispatch code](https://github.com/oasislabs/oasis-rs/blob/master/oasis-build/src/gen/dispatcher.rs#L122-L127) for you. Basically what happens is 
1. the contract requests the input (i.e. `payload`), which is encoded as `fn_index || encoded_fn_args`
2. it deserializes the input as a tagged union (the tag is the requested function, the other members are the args)
3. it `match`es the tag and dispatches the args to the method you wrote

The client's [generated code](https://github.com/oasislabs/oasis-cli/blob/master/src/gen/typescript.rs#L467-L475) packs the payload up in the expected format.

>  Oasis nodes test the submitted models against the secret test data

Yes and no. The current [`SANDBOXED_EVALUATOR_IMAGE`](https://github.com/oasislabs/ready-layer-two/blob/master/app/src/evaluator.ts#L123) actually bakes in the evaluation program, which isn't ideal because then you'd need to trust the evaluation program (possibly through auditing, possibly through static analysis). Otherwise, you'd take the evaluator image and make _that_ a sandbox in which you run the untrusted evaluation program. This demo was written with the assumption that the target environment is a whole-VM enclave like that offered by AMD SEV(-SNP). If you wanted to use a linked-library enclave, you'd need to retool the sandbox a bit and do some trickery for running the evaluation program (e.g., by embedding a python interpreter).

**Comment by luketchang** [comment]
Ahh ok I see wow. Thanks so much for all of this info. This honestly clears up SO MUCH confusion!

**Comment by nhynes** [comment]
Cool, glad it makes sense! I'll close this issue for now, but you should feel encouraged to reopen it or make a new one if you have any other questions.
